---
{{- $secretName := "db-password" }}
{{- $keyName := "password" }}
{{- $env := .Values.env }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-argo-secrets
spec:
  releaseName: {{ .Release.Name }}-argo-secrets
  targetNamespace: secrets-manager
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm
    name: create-secret-manager-secret
    version: 0.0.5
  values:
    secrets:
      - secretName: {{ $secretName }}
        nameSpace: {{ .Values.namespace }}
        vals:
          - kubeSecretKey: {{ $keyName }}
            path: {{ .Values.vaultPrefix }}/cloudsql/users/argo
            vaultKey: password
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-argo-controller
spec:
  releaseName: {{ .Release.Name }}-argo
  targetNamespace: {{ .Values.namespace }}
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/monster-helm
    name: argo-controller
    version: 0.7.5
  values:
    logs:
      bucket: {{ .Values.artifactBucket }}
    clusterName: command-center-cluster
    debug: {{ eq $env "dev" }}
    persistence:
      host: cloudsql-proxy-gcloud-sqlproxy.cloudsql-proxy
      port: 5432
      database: argo
      username: argo
      password:
        secretName: {{ $secretName }}
        secretKey: {{ $keyName }}
    workflowDefaults:
      {{ $isDev := eq $env "dev" }}
      podGarbageCollection:
        enabled: true
        strategy: OnPodSuccess
      workflowTTL:
        enabled: true
        {{- /*
             * Timing translations:
             *   - In dev, keep successes for 1 day, failures for a week
             *   - In prod, keep successes for 1 hour, failures for 3 days
             */}}
        secondsAfterSuccess: {{ if $isDev }}86400{{ else }}3600{{ end }}
        secondsAfterFailure: {{ if $isDev }}604800{{ else }}259200{{ end }}
