###
## Permissions required to run pods in one of our clusters.
###
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: pod-running-policy
spec:
  privileged: true
  allowedCapabilities:
    - IPC_LOCK
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
