enable: false
argo:
  env: prod
  vaultPrefix: secret/dsde/monster/prod/command-center
  namespace: clinvar
  artifactBucket: broad-dsp-monster-clingen-prod-argo-archive
chart:
  git: false
  ref: 1.0.0-RC1
repo:
  url: https://jade-terra.datarepo-prod.broadinstitute.org
  dataProject: broad-datarepo-terra-prod-cgen
  datasetName: broad_dsp_clinvar
  datasetId: f8818986-2b81-4487-a7df-6e166d4c87a7
  profileId: 5c001e19-ea18-41e4-8671-de42503fadcc
notification:
  onlyOnFailure: false
  vaultSecret:
    path: secret/dsde/monster/prod/clingen/slack-notifier
    key: url
