enable: true
schedule: '0 13 * * *'
argo:
  env: prod
  vaultPrefix: secret/dsde/monster/prod/command-center
  namespace: clinvar
  artifactBucket: broad-dsp-monster-clingen-prod-argo-archive
chart:
  git: false
  ref: 1.2.9
repo:
  url: https://jade-terra.datarepo-prod.broadinstitute.org
  dataProject: broad-datarepo-terra-prod-cgen
  datasetName: broad_dsp_clinvar
  datasetId: dfbd0c7e-088b-45ab-a161-7b79aa28d872
  profileId: 5c001e19-ea18-41e4-8671-de42503fadcc
notification:
  onlyOnFailure: false
  vaultSecret:
    path: secret/dsde/monster/prod/clingen/slack-notifier
    key: url
