enable: true
schedule: '0 20 * * *'
argo:
  env: prod
  vaultPrefix: secret/dsde/monster/prod/command-center
  namespace: clinvar
  artifactBucket: broad-dsp-monster-clingen-prod-argo-archive
chart:
  git: false
  ref: 1.6.58
repo:
  url: https://data.terra.bio
  dataProject: datarepo-4c7e3eea
  datasetName: broad_dsp_clinvar
  datasetId: 29844445-5005-4672-a2f1-f238de23dc20
  profileId: 53cf7db4-1ac5-4a83-b204-95d2fea68ff1
notification:
  altChannelId: clinvar-migration-notifications
  channelId: clinvar-ingest
  onlyOnFailure: false
  vaultSecret:
    path: secret/dsde/monster/prod/slack-notifier
    key: oauth_token
