apiVersion: v2
name: encode-ingest
description: Argo workflow for regular ingest of ENCODE data.
version: 0.0.0
dependencies:
  - name: argo-controller
    version: 0.0.1
    repository: file:///charts/argo-controller
    alias: argo
