---
{{- $secretName := "db-password" }}
{{- $keyName := "password" }}
{{- $env := .Values.env }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: db-login-secrets
spec:
  releaseName: db-login-secrets
  targetNamespace: secrets-manager
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm
    name: create-secret-manager-secret
    version: 0.0.5
  values:
    secrets:
      {{- range $ns := (append .Values.argoNamespaces "argo-ui") }}
      - secretName: {{ $secretName }}
        nameSpace: {{ $ns }}
        vals:
          - kubeSecretKey: {{ $keyName }}
            path: secret/dsde/monster/{{ $env }}/command-center/cloudsql/users/argo
            vaultKey: password
      {{- end }}
{{- /*
  Generate a HelmRelease object per target namespace.

  The leading '---' is needed to properly separate the objects from
  one another within the rendered file.
*/ -}}
{{- range $ns := .Values.argoNamespaces }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: {{$ns}}-argo-controller
spec:
  releaseName: {{$ns}}-argo
  targetNamespace: {{ $ns }}
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/monster-helm
    name: argo-controller
    version: 0.5.0
  values:
    clusterName: command-center-cluster
    debug: {{ eq $env "dev" }}
    persistence:
      host: cloudsql-proxy-gcloud-sqlproxy.cloudsql-proxy
      port: 5432
      database: argo
      username: argo
      password:
        secretName: {{ $secretName }}
        secretKey: {{ $keyName }}
    workflowDefaults:
      {{ $isDev := eq $env "dev" }}
      podGarbageCollection:
        enabled: {{ not $isDev }}
        {{- if not $isDev }}
        strategy: OnWorkflowSuccess
        {{- end }}
      workflowTTL:
        enabled: true
        {{- /*
             * Timing translations:
             *   - In dev, keep successes for 1 day, failures for a week
             *   - In prod, keep successes for 1 hour, failures for 3 days
             */}}
        secondsAfterSuccess: {{ if $isDev }}86400{{ else }}3600{{ end }}
        secondsAfterFailure: {{ if $isDev }}604800{{ else }}259200{{ end }}
{{- end }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: argo-server
spec:
  releaseName: argo
  targetNamespace: argo-ui
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/monster-helm
    name: argo-server
    version: 0.6.0
  values:
    clusterName: command-center-cluster
    stackdriverProject: broad-dsp-monster-{{ .Values.env }}
    debug: {{ eq $env "dev" }}
    persistence:
      host: cloudsql-proxy-gcloud-sqlproxy.cloudsql-proxy
      port: 5432
      database: argo
      username: argo
      password:
        secretName: {{ $secretName }}
        secretKey: {{ $keyName }}
    service:
      ingress:
        create: true
        ipName: argo-ip
        domainName: argo.monster-{{ .Values.env }}.broadinstitute.org
