---
{{- $secretName := "db-password" }}
{{- $keyName := "password" }}
{{- $env := .Values.env }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: db-login-secrets
spec:
  releaseName: db-login-secrets
  targetNamespace: secrets-manager
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm
    name: create-secret-manager-secret
    version: 0.0.5
  values:
    secrets:
      {{- range .Values.argoNamespaces }}
      - secretName: {{ $secretName }}
        nameSpace: {{.}}
        vals:
          - kubeSecretKey: {{ $keyName }}
            path: secret/dsde/monster/{{ $env }}/command-center/cloudsql/users/argo
            vaultKey: password
      {{- end }}
{{- range .Values.argoNamespaces }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: {{.}}-argo-controller
spec:
  releaseName: argo-controller
  targetNamespace: {{.}}
  resetValues: true
  chart:
    git: git://github.com/broadinstitute/monster-helm.git
    ref: dm-argo-controller-DSPDC-671
    path: charts/argo-controller
  values:
    persistence:
      host: cloudsql-proxy-gcloud-sqlproxy.cloudsql-proxy
      port: 5432
      database: command-center-argo
      username: command-center-argo
      password:
        secretName: {{ $secretName }}
        secretKey: {{ $keyName }}
{{- end }}
