{{ $project := printf "broad-dsp-monster-clingen-%s" .Values.env }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: clinvar-orchestration
spec:
  releaseName: clinvar-orchestration
  targetNamespace: clinvar
  resetValues: true
  chart:
    git: git://github.com/databiosphere/clinvar-ingest.git
    ref: master
    path: orchestration
  values:
    gcs:
      bucketName: {{ $project }}-staging-storage
    serviceAccount:
      k8sName: argo-runner
      googleName: clinvar-argo-runner@broad-dsp-monster-{{ .Values.env }}.iam.gserviceaccount.com
    cron:
      # 8:00am every day for now, as we test.
      schedule: "0 8 * * *"
    dataflow:
      project: {{ $project }}
      tmpBucketName: {{ $project }}-temp-storage
      subnetName: monster-processing-network
      workerAccount: dataflow-runner@{{ $project }}.iam.gserviceaccount.com
      useFlexRS: {{ eq .Values.env "prod" }}
    bigquery:
      stagingData:
        project: {{ $project }}
        dataset: monster_staging_data
      jadeData:
        project: {{ if (eq .Values.env "dev") }}broad-jade-dev-data{{ else }}broad-datarepo-terra-prod-cgen{{end}}
