---
{{- $secretName := "cloudsql-proxy-key" }}
{{- $keyName := "key.json" }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cloudsql-proxy-secrets
spec:
  releaseName: cloudsql-proxy-secrets
  targetNamespace: secrets-manager
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm
    name: create-secret-manager-secret
    version: 0.0.5
  values:
    secrets:
      - secretName: {{ $secretName }}
        nameSpace: cloudsql-proxy
        vals:
          - kubeSecretKey: {{ $keyName }}
            path: {{ .Values.vaultPrefix }}/service-accounts/command-center-proxy-runner
            vaultKey: key
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cloudsql-proxy
spec:
  releaseName: cloudsql-proxy
  targetNamespace: cloudsql-proxy
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm
    name: gcloud-sqlproxy
    version: 0.19.6
  values:
    cloudsql:
      instances:
        - instance: {{ .Values.cloudsql.name }}
          project: {{ .Values.cloudsql.project }}
          region: {{ .Values.cloudsql.region }}
          port: 5432
    rbac:
      create: true
    existingSecret: {{ $secretName }}
    existingSecretKey: {{ $keyName }}
