---
{{- $project := "broad-dsp-monster-hca-dev" }}
{{- $secretName := "hca-key" }}
{{- $keyName := "key.json" }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hca-secrets
spec:
  releaseName: hca-secrets
  targetNamespace: secrets-manager
  resetValues: true
  chart:
    repository: https://broadinstitute.github.io/datarepo-helm
    name: create-secret-manager-secret
    version: 0.0.5
  values:
    secrets:
      - secretName: {{ $secretName }}
        nameSpace: hca-mvp
        vals:
          - kubeSecretKey: {{ $keyName }}
            path: secret/dsde/monster/dev/ingest/hca/service-accounts/hca-argo-runner
            vaultKey: key
---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hca-orchestration
spec:
  releaseName: hca-orchestration
  targetNamespace: hca-mvp
  resetValues: true
  chart:
    git: git://github.com/databiosphere/hca-ingest.git
    ref: master
    path: orchestration
  values:
    gcs:
      stagingBucketName: {{ $project }}-staging-storage
    serviceAccount:
      k8sName: argo-runner
      googleName: hca-argo-runner@{{ $project }}.iam.gserviceaccount.com
    cron:
      enable: {{ .Values.enable }}
      {{- if .Values.schedule }}
      schedule: {{ .Values.schedule }}
      {{- end }}
    dataflow:
      project: {{ $project }}
      tmpBucketName: {{ $project }}-temp-storage
      subnetName: hca-network
      workerAccount: hca-dataflow-runner@{{ $project }}.iam.gserviceaccount.com
      useFlexRS: {{ eq .Values.env "prod" }}
    bigquery:
      stagingData:
        project: {{ $project }}
        datasetPrefix: ingest_staging
        description: 'Temporary storage for HCA ingest'
        # 7 days in units of seconds
        expiration: '604800'
      jadeData:
        # FIXME: Parameterize for prod.
        project: broad-jade-dev-data
        dataset: datarepo_hca_mvp
    repo:
      # TODO: Switch on environment
      url: https://jade.datarepo-dev.broadinstitute.org
      datasetId: 8c6633e3-ce9c-4aa4-b0ae-3fba122386a1
      profileId: 390e7a85-d47f-4531-b612-165fc977d3bd
      accessKey:
        secretName: {{ $secretName }}
        secretKey: {{ $keyName }}
