#!/usr/bin/env bash
set -euo pipefail

declare -r SCRIPT_DIR=$(cd $(dirname ${0}) >/dev/null 2>&1 && pwd)
declare -r REPO_ROOT=$(cd $(dirname ${SCRIPT_DIR}) >/dev/null 2>&1 && pwd)

declare -r ARGO_VERSION=v2.7.1
declare -r PROMETHEUS_OPERATOR_VERSION=release-0.36

declare -ra CRDS=(
  https://raw.githubusercontent.com/argoproj/argo/${ARGO_VERSION}/manifests/base/crds/workflow-crd.yaml
)

declare -ra COMMAND_CENTER_NAMESPACES=(
  cloudsql-proxy
  argo-ui
  monitoring
)

declare -rA IP_PREFIXES=(
  [dev]=''
  [hca]=hca-
  [prod]=''
  [hca-prod]=hca-
)

declare -rA DEBUG=(
  [dev]=true
  [hca]=true
  [prod]=false
  [hca-prod]=false
)

declare -rA DNS_ZONES=(
  [dev]=monster-dev
  [hca]=monster-dev
  [prod]=monster-prod
  [hca-prod]=monster-prod
)

declare -rA STACKDRIVER_PROJECTS=(
  [dev]=broad-dsp-monster-dev
  [hca]=broad-dsp-monster-hca-dev
  [prod]=broad-dsp-monster-prod
  [hca-prod]=broad-dsp-monster-prod
)

source ${SCRIPT_DIR}/common.sh

#####
## Deploy a bundle of release definitions into the command-center cluster
## for an environment.
##
## NOTE: This assumes that fluxcd and the secrets-manager have already been
## installed into the target cluster.
#####
function install_command_center_services () {
  local -r kubeconfig=$1 env=$2 helm_dir=$3

  local -ra helm=($(configure_helm ${kubeconfig} ${helm_dir} ${env}))
  local -r vault_prefix=${VAULT_PREFIXES[${env}]}
  local -r sql_instance_secret=${vault_prefix}/cloudsql/instance
  local -r ip_prefix=${IP_PREFIXES[${env}]}

  ${helm[@]} dependency update /charts/command-center
  ${helm[@]} upgrade command-center /charts/command-center \
   --namespace fluxcd \
   --install \
   --set "vaultPrefix=${vault_prefix}" \
   --set "cloudsql.name=$(vault read -field=name ${sql_instance_secret})" \
   --set "cloudsql.project=$(vault read -field=project ${sql_instance_secret})" \
   --set "cloudsql.region=$(vault read -field=region ${sql_instance_secret})" \
   --set "dns.argo=${ip_prefix}argo" \
   --set "dns.grafana=${ip_prefix}grafana" \
   --set "dns.zone=${DNS_ZONES[${env}]}" \
   --set "stackdriverProject=${STACKDRIVER_PROJECTS[${env}]}" \
   --set "debug=${DEBUG[${env}]}"
}

#####
## Entrypoint to the script.
##
## Ensures all expected Helm charts are released to the
## command-center and processing clusters within a core
## Monster environment.
#####
function main () {
  # Check args.
  if [ $# -ne 1 ]; then
    1>&2 echo Usage: ${0} '<env>'
    exit 1
  fi

  # Make sure config exists.
  local -r env=$1
  local -r env_dir=${REPO_ROOT}/environments/${env}
  if [ ! -d ${env_dir} ]; then
    1>&2 echo Error: Invalid environment "'$1'"
    exit 1
  fi

  local -r config_dir=${env_dir}/.kubeconfig
  mkdir -p ${config_dir}

  local -r helm_dir=${env_dir}/.helm
  mkdir -p ${helm_dir}

  # Push releases to the command center.
  local -r center_config=${config_dir}/command-center
  get_command_center_config ${env} ${center_config}
  apply_namespaces ${center_config} ${COMMAND_CENTER_NAMESPACES[@]}
  apply_urls ${center_config} ${CRDS[@]}
  install_command_center_services ${center_config} ${env} ${helm_dir}
  fire_slack_deployment_notification "command center" ${env}
}

main ${@}
