#!/usr/bin/env python3

import argparse
from google.oauth2.service_account import Credentials
from google.auth.transport.requests import AuthorizedSession

DEV_SAM = 'https://sam.dsde-dev.broadinstitute.org/'
PROD_SAM = ''

parser = argparse.ArgumentParser(description='Register a Google service account in Terra')
parser.add_argument('-k', '--sa-key', action='store', dest='sa_key')
parser.add_argument('-e', '--terra-env', action='store', dest='env', choices=['dev', 'prod'])

args = parser.parse_args()

service_account_creds = Credentials.from_service_account_file(args.sa_key, scopes=['openid', 'email', 'profile'])
authorized_session = AuthorizedSession(service_account_creds)

sam_base = f'https://sam.dsde-{args.env}.broadinstitute.org/register/user/v2/self'
authorized_session.post(sam_base)
