enable: true
schedule: '0 8 * * 1'
argo:
  env: prod
  vaultPrefix: secret/dsde/monster/prod/command-center
  namespace: encode
  artifactBucket: broad-dsp-monster-encode-prod-argo-archive
repo:
  profileId: afc84cc8-e1ba-48d6-8153-dbc1d3f52c37
  datasetId: 409b4c5e-564f-48fc-b590-cb4763234115
  datasetName: broad_dsp_encode
  dataProject: broad-datarepo-terra-prod-encd
  url: https://jade-terra.datarepo-prod.broadinstitute.org
chart:
  git: false
  ref: 1.0.0-M2
