enable: true
schedule: '52 12 * * *'
argo:
  env: prod
  vaultPrefix: secret/dsde/monster/prod/command-center
  namespace: encode
  artifactBucket: broad-dsp-monster-encode-prod-argo-archive
repo:
  profileId: 0e6dd763-e8ef-4aad-bc99-f0fc7bbf2a76
  datasetId: 401d88ae-563a-436c-b9c1-2f5313582b50
  datasetName: encode_in_anvil_v6
  dataProject: datarepo-e161cb6b
  url: https://data.terra.bio
chart:
  git: false
  ref: 1.0.119
