name: Set Up Terraform
description: Configure the environment to run Terraform commands
inputs:
  environment:
    description: Which environment to initialize
    required: true
  vault_env:
    description: Vault environment to load
    required: true
  vault_role_id_secret:
    description: Github secret containing the role ID for Vault authentication
    required: true
  vault_secret_id_secret:
    description: Github secret containing the secret for Vault authentication
    required: true
  terraform_version:
    description: Version of Terraform to install
    required: true
    default: "0.12.24"
outputs:
  terraform-directory:
    description: Directory containing Terraform config that has been initialized
    value: "${{ steps.terraform-dir.outputs.terraform_directory }}"
  vault-token:
    description: "Token used to authenticate to Vault to fetch secrets"
    value: "${{ steps.token.outputs.vault_token }}"

runs:
  using: composite
  runs-on: ubuntu-latest
  steps:
    - name: "${{ inputs.environment }} Checkout"
      uses: actions/checkout@v2

    - name: compute terraform directory
      id: terraform-dir
      run: echo "::set-output name=terraform_directory::${{ github.workspace }}/environments/${{ inputs.environment }}/terraform"

    - name: install terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: "${{ inputs.environment }} set VAULT_TOKEN"
      id: token
      run: |
        VAULT_TOKEN=$(curl \
          --request POST \
          --data '{"role_id":"'"${ROLE_ID}"'","secret_id":"'"${SECRET_ID}"'"}' \
          ${VAULT_ADDR}/v1/auth/approle/login | jq -r .auth.client_token)
        echo ::add-mask::${VAULT_TOKEN}
        echo "VAULT_TOKEN=$(echo ${VAULT_TOKEN})" >> $GITHUB_ENV
        echo ::set-output name=vault_token::${VAULT_TOKEN}
      env:
        ROLE_ID: ${{ secrets[inputs.vault_role_id_secret] }}
        SECRET_ID: ${{ secrets[inputs.vault_secret_id_secret] }}
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}


    - name: "${{ inputs.environment }} consul-template render templates for terraform"
      uses: broadinstitute/github-action-consul-template@master
      with:
        vault-address: ${{ secrets.VAULT_ADDR }}
        vault-token: ${{ steps.token.outputs.vault_token }}
        environment: ${{ inputs.vault_env }}
        env_path: "environments"

    - name: "${{ inputs.environment }} - Terraform Init"
      id: init
      run: terraform init ${{ steps.terraform-dir.outputs.terraform_directory }}
      env:
        VAULT_TOKEN: ${{ steps.token.outputs.vault_token }}
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/environments/gcs_sa_key.json"
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
