enable: true
schedule: '0 12 * * *'
argo:
  env: dev
  vaultPrefix: secret/dsde/monster/dev/command-center
  namespace: encode
  artifactBucket: broad-dsp-monster-encode-dev-argo-archive
chart:
  git: false
  ref: 1.0.5
repo:
  url: https://jade.datarepo-dev.broadinstitute.org
  dataProject: datarepo-dev-6ba96183
  datasetName: encode_2022_us
  datasetId: 3e8d5e37-90f4-43b7-8e2a-6c233b0032c4
  profileId: 390e7a85-d47f-4531-b612-165fc977d3bd
