name: Check Terraform Security
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --concise-output --no-code --soft-fail --no-ignores --no-color --minimum-severity=HIGH --format=csv,json
          tfsec_formats: csv,json
          github_token: ${{ github.token }}

      - name: Commit tfsec results
        run: |
          git config --local user.email "
          git config --local user.name "
          git add .
          git commit -m "Add tfsec results"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true

